services:
  decksplain:
    build: .
    ports:
      - "5000:5000"
    environment:
      # GitHub Pages base path
      - BASE_PATH=/
      # GitHub Pages Domain
      - BASE_URL
    volumes:
      - ./static:/app/static
